
#MENU
DELETE FROM T1_MENU;
#Proses Pengadaan
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(1, '2015-11-19 17:00:00', NULL, 0, 'Proses Pengadaan', NULL, NULL, NULL, NULL, 'icon-loader', 10);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(2, '2015-11-21 08:19:47', NULL, 0, 'Inisialisasi Pengadaan', 83, 'app.promise.procurement-inisialisasi', NULL, NULL, 'icon-play',1);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(3, '2015-11-21 08:14:30', NULL, 0, 'Pengadaan Private Sector', 83, 'app.promise.procurement-inisialisasi-smb', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(4, '2015-11-26 16:31:11', NULL, 0, 'Manajemen SPK', NULL, NULL, NULL, NULL, 'icon-paper-stack',30);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(5, '2015-11-26 16:32:57', NULL, 0, 'Pembuatan SPK', 4, 'app.promise.procurement-panitia-spk', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(6, '2015-11-26 16:33:20', NULL, 0, 'Monitoring SPK', 4, 'app.promise.procurement-panitia-spk-index', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(7, '2015-11-30 04:46:19', NULL, 0, 'Jadwal Pengadaan', 1, 'app.promise.procurement-jadwalpengadaan', '2015-11-30 11:51:05', 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(8, '2015-11-30 04:53:25', NULL, 0, 'Pengambilan Dokumen', 1, 'app.promise.procurement-panitia-pengambilandokumen', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(9, '2015-11-30 04:54:06', NULL, 0, 'Kriteria Evaluasi', 1, 'app.promise.procurement-panitia-kriteriaEvaluasi', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(10, '2015-11-30 04:54:27', NULL, 0, 'Penjelasan', 1, 'app.promise.procurement-panitia-penjelasan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(11, '2015-11-30 04:54:59', NULL, 0, 'Pemasukan Penawaran', 1, 'app.promise.procurement-panitia-pemasukanPenawaran', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(12, '2015-11-30 06:54:53', NULL, 0, 'Pembukaan Penawaran', 1, 'app.promise.procurement-panitia-pembukaanPenawaran', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(13, '2015-11-30 06:55:20', NULL, 0, 'Evaluasi Administrasi', 1, 'app.promise.procurement-panitia-evaluasiAdministrasi', '2015-11-30 14:10:12', 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(14, '2015-11-30 06:55:39', NULL, 0, 'Evaluasi Teknis', 1, 'app.promise.procurement-panitia-evaluasiteknis', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(15, '2015-11-30 06:56:09', NULL, 0, 'Evaluasi Harga Auction', 1, 'app.promise.procurement-panitia-evaluasiharga-auction', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(16, '2015-11-30 06:56:32', NULL, 0, 'Evaluasi Harga Bidding', 1, 'app.promise.procurement-panitia-evaluasiharga-bidding', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(17, '2015-11-30 06:56:51', NULL, 0, 'Negosiasi', 1, 'app.promise.procurement-panitia-negosiasi', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(18, '2015-11-30 06:57:06', NULL, 0, 'Penetapan Pemenang', 1, 'app.promise.procurement-panitia-penetapanpemenang', NULL, 0, 'icon-play');
#Master
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(19, '2015-11-30 06:59:26', NULL, 0, 'Master Data', NULL, NULL, NULL, NULL, 'icon-server', 90);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(20, '2015-11-30 07:00:29', NULL, 0, 'Setting', NULL, NULL, NULL, NULL, 'icon-cog', 80);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(21, '2015-11-30 07:07:28', NULL, 0, 'Tipe Item', 19, 'app.promise.procurement-master-itemtype', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(22, '2015-11-30 07:07:58', NULL, 0, 'Item Group', 19, 'app.promise.procurement-master-itemgroup', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(23, '2015-11-30 07:08:21', NULL, 0, 'Item', 19, 'app.promise.procurement-master-item', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(24, '2015-11-30 07:09:13', NULL, 0, 'Bidang Usaha', 19, 'app.promise.procurement-master-bidangusaha', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(25, '2015-11-30 07:12:01', NULL, 0, 'Sub Bidang Usaha', 19, 'app.promise.procurement-master-subbidangusaha', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(26, '2015-11-30 07:12:41', NULL, 0, 'Kriteria Administrasi', 19, 'app.promise.procurement-master-kriteriaAdministrasi', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(27, '2015-11-30 07:13:01', NULL, 0, 'Kriteria Teknis', 19, 'app.promise.procurement-master-kriteriaTeknis', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(28, '2015-11-30 07:13:34', NULL, 0, 'User', 19, 'app.promise.procurement-master-user', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(29, '2015-11-30 07:14:01', NULL, 0, 'Pelaksana Pengadaan', 19, 'app.promise.procurement-master-pelaksanapengadaan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(30, '2015-11-30 07:14:34', NULL, 0, 'Organisasi', 20, 'app.promise.procurement-master-organisasi', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(31, '2015-11-30 07:14:53', NULL, 0, 'Tahapan', 20, 'app.promise.procurement-master-tahapan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(32, '2015-11-30 07:15:14', NULL, 0, 'Kondisi Pengadaan', 20, 'app.promise.procurement-master-kondisipengadaan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(33, '2015-11-30 07:15:33', NULL, 0, 'Alur Pengadaan', 20, 'app.promise.procurement-master-alurpengadaan', NULL, 0, 'icon-play',1);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(34, '2015-11-30 07:16:21', NULL, 0, 'Registrasi Jadwal Tahapan Pengadaan', 20, 'app.promise.procurement-master-registrasijadwaltahapanpengadaan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(35, '2015-11-30 07:16:59', NULL, 0, 'Kategori Pengadaan', 20, 'app.promise.procurement-master-kategoripengadaan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(36, '2015-11-30 07:17:26', NULL, 0, 'Termin Kontrak', 20, 'app.promise.procurement-master-terminkontrak', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(37, '2015-11-30 07:17:52', NULL, 0, 'Vendor Requirement', 20, 'app.promise.procurement-master-vendorrequirement', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(38, '2015-11-30 07:18:27', NULL, 0, 'Emai Notifikasi', 20, 'app.promise.procurement-master-emailnotification', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(39, '2015-11-30 07:18:58', NULL, 0, 'Email SMTP Server', 20, 'app.promise.procurement-master-emailsmtp', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(40, '2015-11-30 07:19:46', NULL, 0, 'Conditional Price', 20, 'app.promise.procurement-master-conditionalprize', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(41, '2015-11-30 07:20:08', NULL, 0, 'Jabatan', 20, 'app.promise.procurement-master-jabatan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(42, '2015-11-30 07:20:27', NULL, 0, 'Jenis Pajak', 20, 'app.promise.procurement-master-jenispajak', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(43, '2015-11-30 07:20:50', NULL, 0, 'Jenis Penawaran', 20, 'app.promise.procurement-master-jenispenawaran', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(44, '2015-11-30 07:21:17', NULL, 0, 'Jenis Pengadaan', 20, 'app.promise.procurement-master-jenisPengadaan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(45, '2015-11-30 07:21:49', NULL, 0, 'Kualifikasi Pengadaan', 20, 'app.promise.procurement-master-kualifikasipengadaan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(46, '2015-11-30 07:22:10', NULL, 0, 'Kualifikasi Vendor', 20, 'app.promise.procurement-master-kualifikasivendor', '2015-11-30 14:22:45', 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(47, '2015-11-30 07:23:07', NULL, 0, 'Metode Penawaran Harga', 20, 'app.promise.procurement-master-metodepenawaranharga', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(48, '2015-11-30 07:23:30', NULL, 0, 'Metode Pengadaan', 20, 'app.promise.procurement-master-metodePengadaan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(49, '2015-11-30 07:23:52', NULL, 0, 'Pembuat Keputusan', 20, 'app.promise.procurement-master-pembuatkeputusan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(50, '2015-11-30 07:24:17', NULL, 0, 'Metode Penyampaian Dokumen Pengadaan', 20, 'app.promise.procurement-master-metodePenyampaianDokumenPengadaan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(51, '2015-11-30 07:24:43', NULL, 0, 'Sistem Evaluasi Penawaran', 20, 'app.promise.procurement-master-sistemevaluasipenawaran', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(52, '2015-11-30 07:25:14', NULL, 0, 'Satuan', 20, 'app.promise.procurement-master-satuan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(53, '2015-11-30 07:25:35', NULL, 0, 'Mata Uang', 20, 'app.promise.procurement-master-matauang', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(54, '2015-11-30 07:25:49', NULL, 0, 'Aksi', 20, 'app.promise.procurement-master-aksi', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(55, '2015-11-30 07:26:13', NULL, 0, 'Menu', 20, 'app.promise.procurement-master-menu', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(56, '2015-11-30 07:26:33', NULL, 0, 'Menu Aksi', 20, 'app.promise.procurement-master-menuaksi', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(57, '2015-11-30 07:26:52', NULL, 0, 'Role Menu', 20, 'app.promise.procurement-master-rolemenu', NULL, 0, 'icon-play');

#Proses PengadaanVendor
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(58, '2015-11-30 09:01:10', NULL, 0, 'Proses Pengadaan Vendor', NULL, NULL, NULL, NULL, 'icon-briefcase',2);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(59, '2015-11-30 09:02:06', NULL, 0, 'Pengumuman Pengadaan', 58, 'appvendor.promise.procurement-vendor-pengumumanpengadaan', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(60, '2015-11-30 09:02:33', NULL, 0, 'Undangan Pengadaan', 58, 'appvendor.promise.procurement-undanganvendor', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(61, '2015-11-30 09:03:39', NULL, 0, 'Data Penawaran', NULL, 'appvendor.promise.procurement-vendor-datapenawaran', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(62, '2015-11-30 09:04:16', NULL, 0, 'Penawaran Harga', 58, 'appvendor.promise.procurement-vendor-penawaranharga', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(63, '2015-11-30 09:05:48', NULL, 0, 'Negosiasi', 58, 'appvendor.promise.procurement-vendor-negosiasi', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(64, '2015-11-30 09:06:45', NULL, 0, 'Penawaran Harga Auction', NULL, 'appvendor.promise.procurement-vendor-auctionvendortotal', NULL, NULL, 'icon-play');
#Setting Vendor
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(65, '2015-11-30 09:07:53', NULL, 0, 'Setting', NULL, NULL, NULL, NULL, 'icon-cog',10);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(66, '2015-11-30 09:09:56', NULL, 0, 'Data User', 65, 'appvendor.promise.procurement-vendor-datauser', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(67, '2015-11-30 09:10:57', NULL, 0, 'Data Perusahaan', 65, 'appvendor.promise.procurement-vendor-dataperusahaan', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(68, '2015-11-30 09:11:32', NULL, 0, 'Data Pengalaman', 65, 'appvendor.promise.procurement-vendor-datapengalaman', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(69, '2015-11-30 09:12:05', NULL, 0, 'Data Bank', 65, 'appvendor.promise.procurement-vendor-databank', NULL, NULL, 'icon-play');
#Manajemen Konrak
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(70, '2015-11-30 06:59:26', NULL, 0, 'Manajemen Kontrak', NULL, NULL, NULL, NULL, 'icon-server',40);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(71, '2015-11-21 08:19:47', NULL, 0, 'Buat kontrak', 70, 'app.promise.procurement-manajemenkontrak-viewdatapengadaan', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(72, '2015-11-21 08:19:47', NULL, 0, 'Edit Data Kontrak', 70, 'app.promise.procurement-manajemenkontrak-indexdatakontrak', NULL, NULL, 'icon-play');
#Manajemen Vendor
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(73, '2015-11-30 06:59:26', NULL, 0, 'Manajemen Vendor', NULL, NULL, NULL, NULL, 'icon-head',70);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(74, '2015-11-30 06:59:26', NULL, 0, 'Approval Vendor', 73, 'app.promise.procurement-vendor-approval', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(75, '2015-11-30 09:02:33', NULL, 0, 'Hasil Pengadaan', 58, 'appvendor.promise.procurement-hasilpengadaan', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(76, '2015-11-30 06:59:26', NULL, 0, 'Daftar Vendor', 73, 'app.promise.procurement-vendor-daftarvendor', NULL, NULL, 'icon-server');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(77, '2015-11-30 09:02:33', NULL, 0, 'Rekap Pengadaan', 1, 'app.promise.procurement-panitia-rekappengadaan-index', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(78, '2015-11-30 09:12:05', NULL, 0, 'Data Segmentasi', 65, 'appvendor.promise.procurement-vendor-datasegmentasi', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(79, '2015-11-30 09:12:05', NULL, 0, 'Data Keuangan', 65, 'appvendor.promise.procurement-vendor-datakeuangan', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(80, '2015-11-30 09:12:05', NULL, 0, 'Data Dokumen', 65, 'appvendor.promise.procurement-vendor-datadokumen', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(81, '2015-11-30 09:12:05', NULL, 0, 'Data Peralatan', 65, 'appvendor.promise.procurement-vendor-dataperalatan', NULL, NULL, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(82, '2015-11-30 09:02:33', NULL, 0, 'Seleksi Pendaftaran', 1, 'app.promise.procurement-panitia-seleksipendaftaran-index', NULL, NULL, 'icon-play');
#PraPengadaan
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(83, '2016-01-07 17:00:00', NULL, 0, 'Pra Pengadaan', NULL, NULL, NULL, NULL, 'fa fa-trello', 1);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(84, '2016-01-08 08:19:47', NULL, 0, 'Kriteria Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-kriteriakualifikasi', NULL, NULL, 'icon-play',8);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(85, '2015-11-30 07:12:41', NULL, 0, 'Kriteria Kualifikasi Administrasi', 19, 'app.promise.procurement-master-kriteriaKualifikasiAdministrasi', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(86, '2015-11-30 07:12:41', NULL, 0, 'Parameter', 20, 'app.promise.procurement-master-parameter', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(88, '2015-01-12 07:12:41', NULL, 0, 'Dashboard Panitia', null, 'app.dashboard', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(89, '2015-01-12 07:12:41', NULL, 0, 'Dashboard Vendor', null, 'appvendor.promise.dashboard', NULL, 0, 'icon-play');
#Data_Penawaran_Tahap_Dua
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(90, '2015-11-30 09:03:39', NULL, 0, 'Data Penawaran Tahap Dua', 58, 'appvendor.promise.procurement-vendor-datapenawarantahapdua-index', NULL, NULL, 'icon-play');
#Pembukaan_Penawaran
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(91, '2015-11-30 06:54:53', NULL, 0, 'Pembukaan Penawaran Tahap Satu', 1, 'app.promise.procurement-panitia-pembukaanPenawaran', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(92, '2015-11-30 06:54:53', NULL, 0, 'Pembukaan Penawaran Tahap Dua', 1, 'app.promise.procurement-panitia-pembukaanPenawaran', NULL, 0, 'icon-play');
#Menu_Sanggahan
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(96, '2015-11-30 06:54:53', NULL, 0, 'Penyampaian Sanggahan', 58, 'appvendor.promise.procurement-vendor-sanggahan', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(97, '2015-11-30 06:54:53', NULL, 0, 'Sanggahan', 1, 'app.promise.procurement-panitia-sanggahan', NULL, 0, 'icon-play');
#Alokasi Anggaran
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(98, '2015-11-30 06:54:53', NULL, 0, 'Anggaran', NULL, NULL, NULL, 0, 'icon-layers', 1);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(99, '2015-11-30 06:54:53', NULL, 0, 'Alokasi Anggaran', 98, 'app.promise.procurement-panitia-alokasianggaran', NULL, 0, 'icon-play', 1);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(100, '2015-11-30 06:54:53', NULL, 0, 'Anggaran Gabungan', 98, 'app.promise.procurement-panitia-alokasianggaran-gabung', NULL, 0, 'icon-play', 3);
#Perencanaan
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(101, '2015-11-30 06:54:53', NULL, 0, 'Perencanaan', NULL, NULL, NULL, 0, 'icon-clock', 1);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(102, '2015-11-30 06:54:53', NULL, 0, 'Perencanaan Pengadaan', 101, 'app.promise.procurement-panitia-perencanaan', NULL, 0, 'icon-play');
#Purchase Request
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(206, '2016-08-25 07:00:29', NULL, 0, 'Purchase Request', 101, 'app.promise.procurement-purchaserequest', NULL, NULL, 'icon-play');
#Pengumuman Evaluasi Admin Teknis
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(103, '2015-11-30 06:54:53', NULL, 0, 'Pengumuman Evaluasi Admin Teknis', 1, 'app.promise.procurement-panitia-pengumumanevaluasiadminteknis', NULL, 0, 'icon-play');
#Persetujuan Pengadaan
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(104, '2015-11-30 06:54:53', NULL, 0, 'Persetujuan Pengadaan', 1, 'app.promise.procurement-panitia-persetujuanpengadaan', NULL, 0, 'icon-play',4);
#Jadwal Kualifikasi
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(105, '2015-11-30 06:54:53', NULL, 0, 'Jadwal Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-jadwalkualifikasi', NULL, 0, 'icon-play',5);
#Pengambilan Dokumen Kualifikasi
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(106, '2015-11-30 06:54:53', NULL, 0, 'Pengambilan Dokumen Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-pengambilandokumenkualifikasi', NULL, 0, 'icon-play',7);
#Pemasukan Dokumen Kualifikasi
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(107, '2015-11-30 06:54:53', NULL, 0, 'Pemasukan Dokumen Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-pemasukandokumenkualifikasi', NULL, 0, 'icon-play',8);
#Seleksi Kualifikasi
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(108, '2015-11-30 06:54:53', NULL, 0, 'Seleksi Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-seleksikualifikasi', NULL, 0, 'icon-play',9);
#Hasil Kualifikasi
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(109, '2015-11-30 06:54:53', NULL, 0, 'Hasil Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-hasilkualifikasi', NULL, 0, 'icon-play',10);
#Pembuktian Kualifikasi
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(111, '2015-11-30 06:54:53', NULL, 0, 'Pembuktian Kualifikasi', 1, 'app.promise.procurement-panitia-pembuktiankualifikasi', NULL, 0, 'icon-play',11);
#Proses Pengadaan 1 Sampul
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(112, '2015-11-19 17:00:00', NULL, 0, 'Pengadaan 1 Sampul', NULL, NULL, NULL, NULL, 'icon-loader', 5);
#Proses Pengadaan 2 Sampul
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(113, '2015-11-19 17:00:00', NULL, 0, 'Pengadaan 2 Sampul', NULL, NULL, NULL, NULL, 'icon-loader', 6);
#Proses Pengadaan 2 Tahap
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(114, '2015-11-19 17:00:00', NULL, 0, 'Pengadaan 2 Tahap', NULL, NULL, NULL, NULL, 'icon-loader', 7);
#Proses Pengadaan Pemenang
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(115, '2015-11-19 17:00:00', NULL, 0, 'Pemenang Pengadaan', NULL, NULL, NULL, NULL, 'icon-loader', 8);
#Penilaian Vendor
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(116, '2015-11-30 06:59:26', NULL, 0, 'Penilaian Vendor', 73, 'app.promise.procurement-manajemenvendor-penilaian', NULL, NULL, 'icon-server', 3);
#Inisialiasi Pengadaan Versi 04 - Astra Requirement
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(117, '2015-11-21 08:19:47', NULL, 0, 'Inisialisasi Pengadaan Versi 04', 83, 'app.promise.procurement-inisialisasi-index04', NULL, NULL, 'icon-play',1);
#Proses Pengadana - Usulan Calon Pemenang
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(118, '2015-11-21 08:19:47', NULL, 0, 'Usulan Calon Pememenang', 1, 'app.promise.procurement-panitia-usulancalonpemenang', NULL, NULL, 'icon-play',1);
#Alokasi Anggaran - Versi 02 / Astra
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(119, '2015-11-21 08:19:47', NULL, 0, 'Alokasi Anggaran - Versi 02', 98, 'app.promise.procurement-alokasianggaran-index02', NULL, NULL, 'icon-play',2);

#Pra Kualifikasi Vendor
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(200, '2016-01-07 17:00:00', NULL, 0, 'Pra Pengadaan - Kualifikasi', NULL, NULL, NULL, NULL, 'fa fa-trello',1);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(201, '2016-01-07 17:00:00', NULL, 0, 'Undangan Kualifikasi', 200, 'appvendor.promise.procurement-prakualifikasi-undanganvendorkualifikasi', NULL, NULL, 'icon-play',1);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(202, '2016-01-07 17:00:00', NULL, 0, 'Pengumuman Kualifikasi', 200, 'appvendor.promise.procurement-prakualifikasi-pengumumankualifikasi', NULL, NULL, 'icon-play',2);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(203, '2016-01-07 17:00:00', NULL, 0, 'Data Kualifikasi', 200, 'appvendor.promise.procurement-prakualifikasi-datakualifikasi', NULL, NULL, 'icon-play',3);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(204, '2015-11-30 06:54:53', NULL, 0, 'Hasil Kualifikasi', 200, 'appvendor.promise.procurement-panitia-prakualifikasi-hasilkualifikasi', NULL, 0, 'icon-play',10);

#Rekap History Vendor
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(205, '2015-11-30 06:59:26', NULL, 0, 'Rekap History Vendor', 73, 'app.promise.procurement-manajemenvendor-rekaphistoryvendor', NULL, NULL, 'icon-server', 3);

#Approval
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(300, '2016-01-07 17:00:00', NULL, 0, 'Approval', NULL, NULL, NULL, NULL, 'fa fa-trello',0);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(302, '2015-11-30 07:07:28', NULL, 0, 'Daftar Approval', 300, 'app.promise.procurement-approval', NULL, 0, 'icon-play');
#Approval-Setting
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(301, '2015-11-30 07:07:28', NULL, 0, 'Approval Master', 20, 'app.promise.procurement-master-approval', NULL, 0, 'icon-play');
#Approval-History
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(303, '2015-11-30 07:07:28', NULL, 0, 'Approval History', 300, 'app.promise.procurement-approval-history', NULL, 0, 'icon-play');
#Purchase Order
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(400, '2016-01-07 17:00:00', NULL, 0, 'Purchase Order', NULL, NULL, NULL, NULL, 'fa fa-trello',50);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(401, '2015-11-30 07:07:28', NULL, 0, 'Purchase Order Manager', 400, 'app.promise.procurement-purchaseorder', NULL, 0, 'icon-play');

#Purchase Request Validation
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(410, '2015-11-30 07:07:28', NULL, 0, 'Purchase Request', NULL, NULL, NULL, 0, 'fa fa-trello', 2);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(411, '2015-11-30 07:07:28', NULL, 0, 'Purchase Request Verification', 410, 'app.promise.procurement-purchaserequestverification', NULL, 0, 'icon-play');

#Purchase Request Consolidation
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(803, '2015-11-30 07:07:28', NULL, 0, 'Purchase Request Konsolidasi', 410, 'app.promise.procurement-purchaserequestconsolidation', NULL, 0, 'icon-play');

#Request For Quotation
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(500, '2016-01-07 17:00:00', NULL, 0, 'Request For Quotation', NULL, NULL, NULL, NULL, 'fa fa-trello',20);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(501, '2015-11-30 07:07:28', NULL, 0, 'RFQ Manager', 500, 'app.promise.procurement-requestforquotation', NULL, 0, 'icon-play');

#Delivery Received
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(600, '2016-01-07 17:00:00', NULL, 0, 'Delivery Received', NULL, NULL, NULL, NULL, 'fa fa-trello',60);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(601, '2015-11-30 07:07:28', NULL, 0, 'Delivery Received Manager', 600, 'app.promise.procurement-deliveryreceived', NULL, 0, 'icon-play');
##VENDOR
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(602, '2016-01-07 17:00:00', NULL, 0, 'Delivery Received', NULL, NULL, NULL, NULL, 'fa fa-trello',2);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(603, '2015-11-30 07:07:28', NULL, 0, 'Delivery Received Manager', 602, 'appvendor.promise.procurement-deliveryreceived', NULL, 0, 'icon-play');

#E-Catalog
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(605, '2015-11-30 06:59:26', NULL, 0, 'Catalog', NULL, NULL, NULL, NULL, 'icon-server');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(604, '2015-11-30 07:07:28', NULL, 0, 'Attribute', 605, 'app.promise.procurement-master-attribute', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(606, '2015-11-30 07:07:28', NULL, 0, 'Attribute Group', 605, 'app.promise.procurement-attribute-group', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(607, '2015-11-30 07:07:28', NULL, 0, 'Category', 605, 'app.promise.procurement-category', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(608, '2015-11-30 07:07:28', NULL, 0, 'Manage Catalog', 605, 'app.promise.procurement-catalog', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(609, '2015-11-30 07:07:28', NULL, 0, 'View Vendor', 605, 'app.promise.procurement-catalog-vendor', NULL, 0, 'icon-play');

#KPI Monitoring
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(610, '2016-01-07 17:00:00', NULL, 0, 'KPI Monitoring ', NULL, NULL, NULL, NULL, 'fa fa-trello',70);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(611, '2015-11-30 07:07:28', NULL, 0, 'Monitoring', 610, 'app.promise.procurement-kpimonitoring', NULL, 0, 'icon-play');

# View Catalog
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(612, '2015-11-30 07:07:28', NULL, 0, 'View Catalog', 605, 'app.promise.procurement-ecatalog2', NULL, 0, 'icon-play');

#Invoice Monitoring
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(700, '2015-11-30 06:59:26', NULL, 0, 'Invoice Monitoring', NULL, NULL, NULL, NULL, 'icon-search', 80);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(701, '2015-11-30 07:07:28', NULL, 0, 'Invoice Matching', 700, 'app.promise.procurement-invoicematching', NULL, 0, 'icon-play');

#Catalog Vendor
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(702, '2015-11-30 06:59:26', NULL, 0, 'Catalog Vendor', NULL, NULL, NULL, NULL, 'icon-server');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(703, '2015-11-30 07:07:28', NULL, 0, 'Manage Catalog', 702, 'app.promise.procurement-catalog', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(704, '2015-11-30 07:07:28', NULL, 0, 'View Catalog', 702, 'app.promise.procurement-ecatalog2', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(705, '2015-11-30 07:07:28', NULL, 0, 'View Vendor', 702, 'app.promise.procurement-catalog-vendor', NULL, 0, 'icon-play');

#Catalog Perencana
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(720, '2015-11-30 06:59:26', NULL, 0, 'Catalog Perencana', NULL, NULL, NULL, NULL, 'icon-server');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(721, '2015-11-30 07:07:28', NULL, 0, 'View Catalog', 720, 'app.promise.procurement-ecatalog2', NULL, 0, 'icon-play');

# Master Vendor Performance
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(801, '2015-11-30 07:07:28', NULL, 0, 'Formula Penilaian', 19, 'app.promise.procurement-master-formulapenilaian', NULL, 0, 'icon-play');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(802, '2015-11-30 07:07:28', NULL, 0, 'Indikator Penilaian', 19, 'app.promise.procurement-master-indikatorpenilaian', NULL, 0, 'icon-play');

# Master Alasan Blacklist
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(1003, '2015-11-30 07:07:28', NULL, 0, 'Alasan Blacklist', 19, 'app.promise.procurement-master-alasanblacklist', NULL, 0, 'icon-play');

# Blacklist Vendor
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(1004, '2015-11-30 07:07:28', NULL, 0, 'Blacklist Vendor', 73, 'app.promise.procurement-manajemenvendor-blacklistvendor', NULL, 0, 'icon-play');

# Afco
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(804, '2015-11-30 06:59:26', NULL, 0, 'Afco', NULL, NULL, NULL, NULL, 'icon-server');
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(805, '2015-11-30 07:07:28', NULL, 0, 'Address Book', 803, 'app.promise.procurement-addressbook-index', NULL, 0, 'icon-play');


####  MENU TRANSLATER ###
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (1, '2015-11-19 17:00:00', NULL, 'icon-loader', 0, 'Proses Pengadaan', NULL, NULL, NULL, 10, NULL, 'menu.prosespengadaan.modul_proses_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (2, '2015-11-21 08:19:47', NULL, 'icon-play', 0, 'Inisialisasi Pengadaan', 83, 'app.promise.procurement-inisialisasi', NULL, 1, NULL, 'menu.prapengadaan.inisialisasi_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (3, '2015-11-21 08:14:30', NULL, 'icon-play', 0, 'Pengadaan Private Sector', 83, 'app.promise.procurement-inisialisasi-smb', NULL, 0, NULL, 'menu.prapengadaan.pengadaan_private_sector');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (4, '2015-11-26 16:31:11', NULL, 'icon-paper-stack', 0, 'Manajemen SPK', NULL, NULL, NULL, 30, NULL, 'menu.manajemenspk.modul_manajemen_spk');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (5, '2015-11-26 16:32:57', NULL, 'icon-play', 0, 'Pembuatan SPK', 4, 'app.promise.procurement-panitia-spk', NULL, 0, NULL, 'menu.manajemenspk.pembuatan_spk');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (6, '2015-11-26 16:33:20', NULL, 'icon-play', 0, 'Monitoring SPK', 4, 'app.promise.procurement-panitia-spk-index', NULL, 0, NULL, 'menu.manajemenspk.monitoring_spk');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (7, '2015-11-30 04:46:19', NULL, 'icon-play', 0, 'Jadwal Pengadaan', 1, 'app.promise.procurement-jadwalpengadaan', '2015-11-30 11:51:05', 0, 0, 'menu.prosespengadaan.jadwal_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (8, '2015-11-30 04:53:25', NULL, 'icon-play', 0, 'Pengambilan Dokumen', 1, 'app.promise.procurement-panitia-pengambilandokumen', NULL, 0, 0, 'menu.prosespengadaan.pengambilan_dokumen');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (9, '2015-11-30 04:54:06', NULL, 'icon-play', 0, 'Kriteria Evaluasi', 1, 'app.promise.procurement-panitia-kriteriaEvaluasi', NULL, 0, 0, 'menu.prosespengadaan.kriteria_evaluasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (10, '2015-11-30 04:54:27', NULL, 'icon-play', 0, 'Penjelasan', 1, 'app.promise.procurement-panitia-penjelasan', NULL, 0, 0, 'menu.prosespengadaan.penjelasan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (11, '2015-11-30 04:54:59', NULL, 'icon-play', 0, 'Pemasukan Penawaran', 1, 'app.promise.procurement-panitia-pemasukanPenawaran', NULL, 0, 0, 'menu.prosespengadaan.pemasukan_penawaran');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (12, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Pembukaan Penawaran', 1, 'app.promise.procurement-panitia-pembukaanPenawaran', NULL, 0, 0, 'menu.prosespengadaan.pembukaan_penawaran');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (13, '2015-11-30 06:55:20', NULL, 'icon-play', 0, 'Evaluasi Administrasi', 1, 'app.promise.procurement-panitia-evaluasiAdministrasi', '2015-11-30 14:10:12', 0, 0, 'menu.prosespengadaan.evaluasi_administrasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (14, '2015-11-30 06:55:39', NULL, 'icon-play', 0, 'Evaluasi Teknis', 1, 'app.promise.procurement-panitia-evaluasiteknis', NULL, 0, 0, 'menu.prosespengadaan.evaluasi_teknis');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (15, '2015-11-30 06:56:09', NULL, 'icon-play', 0, 'Evaluasi Harga Auction', 1, 'app.promise.procurement-panitia-evaluasiharga-auction', NULL, 0, 0, 'menu.prosespengadaan.evaluasi_harga_auction');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (16, '2015-11-30 06:56:32', NULL, 'icon-play', 0, 'Evaluasi Harga Bidding', 1, 'app.promise.procurement-panitia-evaluasiharga-bidding', NULL, 0, 0, 'menu.prosespengadaan.evaluasi_harga_bidding');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (17, '2015-11-30 06:56:51', NULL, 'icon-play', 0, 'Negosiasi', 1, 'app.promise.procurement-panitia-negosiasi', NULL, 0, 0, 'menu.prosespengadaan.negosiasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (18, '2015-11-30 06:57:06', NULL, 'icon-play', 0, 'Penetapan Pemenang', 1, 'app.promise.procurement-panitia-penetapanpemenang', NULL, 0, 0, 'menu.prosespengadaan.penetapan_pemenang');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (19, '2015-11-30 06:59:26', NULL, 'icon-server', 0, 'Master Data', NULL, NULL, NULL, 90, NULL, 'menu.masterdata.modul_master_data');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (20, '2015-11-30 07:00:29', NULL, 'icon-cog', 0, 'Setting', NULL, NULL, NULL, 80, NULL, 'menu.settingadmin.modul_setting');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (21, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Tipe Item', 19, 'app.promise.procurement-master-itemtype', NULL, 0, 0, 'menu.masterdata.tipe_item');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (22, '2015-11-30 07:07:58', NULL, 'icon-play', 0, 'Item Group', 19, 'app.promise.procurement-master-itemgroup', NULL, 0, 0, 'menu.masterdata.item_group');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (23, '2015-11-30 07:08:21', NULL, 'icon-play', 0, 'Item', 19, 'app.promise.procurement-master-item', NULL, 0, 0, 'menu.masterdata.item');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (24, '2015-11-30 07:09:13', NULL, 'icon-play', 0, 'Bidang Usaha', 19, 'app.promise.procurement-master-bidangusaha', NULL, 0, 0, 'menu.masterdata.bidang_usaha');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (25, '2015-11-30 07:12:01', NULL, 'icon-play', 0, 'Sub Bidang Usaha', 19, 'app.promise.procurement-master-subbidangusaha', NULL, 0, 0, 'menu.masterdata.sub_bidang_usaha');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (26, '2015-11-30 07:12:41', NULL, 'icon-play', 0, 'Kriteria Administrasi', 19, 'app.promise.procurement-master-kriteriaAdministrasi', NULL, 0, 0, 'menu.masterdata.kriteria_administrasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (27, '2015-11-30 07:13:01', NULL, 'icon-play', 0, 'Kriteria Teknis', 19, 'app.promise.procurement-master-kriteriaTeknis', NULL, 0, 0, 'menu.masterdata.kriteria_teknis');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (28, '2015-11-30 07:13:34', NULL, 'icon-play', 0, 'User', 19, 'app.promise.procurement-master-user', NULL, 0, 0, 'menu.masterdata.user');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (29, '2015-11-30 07:14:01', NULL, 'icon-play', 0, 'Pelaksana Pengadaan', 19, 'app.promise.procurement-master-pelaksanapengadaan', NULL, 0, 0, 'menu.masterdata.pelaksana_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (30, '2015-11-30 07:14:34', NULL, 'icon-play', 0, 'Organisasi', 20, 'app.promise.procurement-master-organisasi', NULL, 0, 0, 'menu.settingadmin.organisasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (31, '2015-11-30 07:14:53', NULL, 'icon-play', 0, 'Tahapan', 20, 'app.promise.procurement-master-tahapan', NULL, 0, 0, 'menu.settingadmin.tahapan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (32, '2015-11-30 07:15:14', NULL, 'icon-play', 0, 'Kondisi Pengadaan', 20, 'app.promise.procurement-master-kondisipengadaan', NULL, 0, 0, 'menu.settingadmin.kondisi_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (33, '2015-11-30 07:15:33', NULL, 'icon-play', 0, 'Alur Pengadaan', 20, 'app.promise.procurement-master-alurpengadaan', NULL, 0, 0, 'menu.settingadmin.alur_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (34, '2015-11-30 07:16:21', NULL, 'icon-play', 0, 'Registrasi Jadwal Tahapan Pengadaan', 20, 'app.promise.procurement-master-registrasijadwaltahapanpengadaan', NULL, 0, 0, 'menu.settingadmin.registrasi_jadwal_tahapan_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (35, '2015-11-30 07:16:59', NULL, 'icon-play', 0, 'Kategori Pengadaan', 20, 'app.promise.procurement-master-kategoripengadaan', NULL, 0, 0, 'menu.settingadmin.kategori_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (36, '2015-11-30 07:17:26', NULL, 'icon-play', 0, 'Termin Kontrak', 20, 'app.promise.procurement-master-terminkontrak', NULL, 0, 0, 'menu.settingadmin.termin_kontrak');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (37, '2015-11-30 07:17:52', NULL, 'icon-play', 0, 'Vendor Requirement', 20, 'app.promise.procurement-master-vendorrequirement', NULL, 0, 0, 'menu.settingadmin.vendor_requirement');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (38, '2015-11-30 07:18:27', NULL, 'icon-play', 0, 'Emai Notifikasi', 20, 'app.promise.procurement-master-emailnotification', NULL, 0, 0, 'menu.settingadmin.email_notifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (39, '2015-11-30 07:18:58', NULL, 'icon-play', 0, 'Email SMTP Server', 20, 'app.promise.procurement-master-emailsmtp', NULL, 0, 0, 'menu.settingadmin.emai_smtp_server');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (40, '2015-11-30 07:19:46', NULL, 'icon-play', 0, 'Conditional Price', 20, 'app.promise.procurement-master-conditionalprize', NULL, 0, 0, 'menu.settingadmin.coditional_price');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (41, '2015-11-30 07:20:08', NULL, 'icon-play', 0, 'Jabatan', 20, 'app.promise.procurement-master-jabatan', NULL, 0, 0, 'menu.settingadmin.jabatan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (42, '2015-11-30 07:20:27', NULL, 'icon-play', 0, 'Jenis Pajak', 20, 'app.promise.procurement-master-jenispajak', NULL, 0, 0, 'menu.settingadmin.jenis_pajak');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (43, '2015-11-30 07:20:50', NULL, 'icon-play', 0, 'Jenis Penawaran', 20, 'app.promise.procurement-master-jenispenawaran', NULL, 0, 0, 'menu.settingadmin.jenis_penawaran');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (44, '2015-11-30 07:21:17', NULL, 'icon-play', 0, 'Jenis Pengadaan', 20, 'app.promise.procurement-master-jenisPengadaan', NULL, 0, 0, 'menu.settingadmin.jenis_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (45, '2015-11-30 07:21:49', NULL, 'icon-play', 0, 'Kualifikasi Pengadaan', 20, 'app.promise.procurement-master-kualifikasipengadaan', NULL, 0, 0, 'menu.settingadmin.kualifikasi_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (46, '2015-11-30 07:22:10', NULL, 'icon-play', 0, 'Kualifikasi Vendor', 20, 'app.promise.procurement-master-kualifikasivendor', '2015-11-30 14:22:45', 0, 0, 'menu.settingadmin.kualifikasi_vendor');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (47, '2015-11-30 07:23:07', NULL, 'icon-play', 0, 'Metode Penawaran Harga', 20, 'app.promise.procurement-master-metodepenawaranharga', NULL, 0, 0, 'menu.settingadmin.metode_penawaran_harga');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (48, '2015-11-30 07:23:30', NULL, 'icon-play', 0, 'Metode Pengadaan', 20, 'app.promise.procurement-master-metodePengadaan', NULL, 0, 0, 'menu.settingadmin.metode_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (49, '2015-11-30 07:23:52', NULL, 'icon-play', 0, 'Pembuat Keputusan', 20, 'app.promise.procurement-master-pembuatkeputusan', NULL, 0, 0, 'menu.settingadmin.pembuat_keputusan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (50, '2015-11-30 07:24:17', NULL, 'icon-play', 0, 'Metode Penyampaian Dokumen Pengadaan', 20, 'app.promise.procurement-master-metodePenyampaianDokumenPengadaan', NULL, 0, 0, 'menu.settingadmin.metode_penyampaian_dokumen_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (51, '2015-11-30 07:24:43', NULL, 'icon-play', 0, 'Sistem Evaluasi Penawaran', 20, 'app.promise.procurement-master-sistemevaluasipenawaran', NULL, 0, 0, 'menu.settingadmin.sistem_evaluasi_penawaran');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (52, '2015-11-30 07:25:14', NULL, 'icon-play', 0, 'Satuan', 20, 'app.promise.procurement-master-satuan', NULL, 0, 0, 'menu.settingadmin.satuan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (53, '2015-11-30 07:25:35', NULL, 'icon-play', 0, 'Mata Uang', 20, 'app.promise.procurement-master-matauang', NULL, 0, 0, 'menu.settingadmin.mata_uang');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (54, '2015-11-30 07:25:49', NULL, 'icon-play', 0, 'Aksi', 20, 'app.promise.procurement-master-aksi', NULL, 0, 0, 'menu.settingadmin.aksi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (55, '2015-11-30 07:26:13', NULL, 'icon-play', 0, 'Menu', 20, 'app.promise.procurement-master-menu', NULL, 0, 0, 'menu.settingadmin.menu');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (56, '2015-11-30 07:26:33', NULL, 'icon-play', 0, 'Menu Aksi', 20, 'app.promise.procurement-master-menuaksi', NULL, 0, 0, 'menu.settingadmin.menu_aksi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (57, '2015-11-30 07:26:52', NULL, 'icon-play', 0, 'Role Menu', 20, 'app.promise.procurement-master-rolemenu', NULL, 0, 0, 'menu.settingadmin.role_menu');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (801, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Formula Penilaian', 19, 'app.promise.procurement-master-formulapenilaian', NULL, 0, 0, 'menu.masterdata.formula_penilaian');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (802, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Indikator Penilaian', 19, 'app.promise.procurement-master-indikatorpenilaian', NULL, 0, 0, 'menu.masterdata.indikator_penilaiain');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (58, '2015-11-30 09:01:10', NULL, 'icon-briefcase', 0, 'Proses Pengadaan Vendor', NULL, NULL, NULL, 2, NULL, 'menu.prosespengadaanvendor.modul_proses_pengadaan_vendor');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (59, '2015-11-30 09:02:06', NULL, 'icon-play', 0, 'Pengumuman Pengadaan', 58, 'appvendor.promise.procurement-vendor-pengumumanpengadaan', NULL, 0, NULL, 'menu.prosespengadaanvendor.pengumuman_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (60, '2015-11-30 09:02:33', NULL, 'icon-play', 0, 'Undangan Pengadaan', 58, 'appvendor.promise.procurement-undanganvendor', NULL, 0, NULL, 'menu.prosespengadaanvendor.undangan_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (61, '2015-11-30 09:03:39', NULL, 'icon-play', 0, 'Data Penawaran', NULL, 'appvendor.promise.procurement-vendor-datapenawaran', NULL, 0, NULL, 'menu.prosespengadaanvendor.data_penawaran');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (62, '2015-11-30 09:04:16', NULL, 'icon-play', 0, 'Penawaran Harga', 58, 'appvendor.promise.procurement-vendor-penawaranharga', NULL, 0, NULL, 'menu.prosespengadaanvendor.penawaran_harga');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (63, '2015-11-30 09:05:48', NULL, 'icon-play', 0, 'Negosiasi', 58, 'appvendor.promise.procurement-vendor-negosiasi', NULL, 0, NULL, 'menu.prosespengadaanvendor.negosiasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (64, '2015-11-30 09:06:45', NULL, 'icon-play', 0, 'Penawaran Harga Auction', NULL, 'appvendor.promise.procurement-vendor-auctionvendortotal', NULL, 0, NULL, NULL);
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (65, '2015-11-30 09:07:53', NULL, 'icon-cog', 0, 'Setting', NULL, NULL, NULL, 10, NULL, 'menu.settingvendor.modul_setting');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (66, '2015-11-30 09:09:56', NULL, 'icon-play', 0, 'Data User', 65, 'appvendor.promise.procurement-vendor-datauser', NULL, 0, NULL, 'menu.settingvendor.data_user');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (67, '2015-11-30 09:10:57', NULL, 'icon-play', 0, 'Data Perusahaan', 65, 'appvendor.promise.procurement-vendor-dataperusahaan', NULL, 0, NULL, 'menu.settingvendor.data_perusahaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (68, '2015-11-30 09:11:32', NULL, 'icon-play', 0, 'Data Pengalaman', 65, 'appvendor.promise.procurement-vendor-datapengalaman', NULL, 0, NULL, 'menu.settingvendor.data_pengalaman');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (69, '2015-11-30 09:12:05', NULL, 'icon-play', 0, 'Data Bank', 65, 'appvendor.promise.procurement-vendor-databank', NULL, 0, NULL, 'menu.settingvendor.data_bank');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (70, '2015-11-30 06:59:26', NULL, 'icon-server', 0, 'Manajemen Kontrak', NULL, NULL, NULL, 40, NULL, 'menu.manajemenkontrak.modul_manajemen_kontrak');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (71, '2015-11-21 08:19:47', NULL, 'icon-play', 0, 'Buat kontrak', 70, 'app.promise.procurement-manajemenkontrak-viewdatapengadaan', NULL, 0, NULL, 'menu.manajemenkontrak.buat_kontrak');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (72, '2015-11-21 08:19:47', NULL, 'icon-play', 0, 'Edit Data Kontrak', 70, 'app.promise.procurement-manajemenkontrak-indexdatakontrak', NULL, 0, NULL, 'menu.manajemenkontrak.edit_data_kontrak');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (73, '2015-11-30 06:59:26', NULL, 'icon-head', 0, 'Manajemen Vendor', NULL, NULL, NULL, 70, NULL, 'menu.manajemenvendor.modul_manajemen_vendor');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (74, '2015-11-30 06:59:26', NULL, 'icon-play', 0, 'Approval Vendor', 73, 'app.promise.procurement-vendor-approval', NULL, 0, NULL, 'menu.manajemenvendor.approval_vendor');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (75, '2015-11-30 09:02:33', NULL, 'icon-play', 0, 'Hasil Pengadaan', 58, 'appvendor.promise.procurement-hasilpengadaan', NULL, 0, NULL, 'menu.prosespengadaanvendor.hasil_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (76, '2015-11-30 06:59:26', NULL, 'icon-server', 0, 'Daftar Vendor', 73, 'app.promise.procurement-vendor-daftarvendor', NULL, 0, NULL, 'menu.manajemenvendor.daftar_vendor');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (77, '2015-11-30 09:02:33', NULL, 'icon-play', 0, 'Rekap Pengadaan', 1, 'app.promise.procurement-panitia-rekappengadaan-index', NULL, 0, NULL, 'menu.prosespengadaan.rekap_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (78, '2015-11-30 09:12:05', NULL, 'icon-play', 0, 'Data Segmentasi', 65, 'appvendor.promise.procurement-vendor-datasegmentasi', NULL, 0, NULL, 'menu.settingvendor.data_segmentasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (79, '2015-11-30 09:12:05', NULL, 'icon-play', 0, 'Data Keuangan', 65, 'appvendor.promise.procurement-vendor-datakeuangan', NULL, 0, NULL, 'menu.settingvendor.data_keuangan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (80, '2015-11-30 09:12:05', NULL, 'icon-play', 0, 'Data Dokumen', 65, 'appvendor.promise.procurement-vendor-datadokumen', NULL, 0, NULL, 'menu.settingvendor.data_dokumen');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (81, '2015-11-30 09:12:05', NULL, 'icon-play', 0, 'Data Peralatan', 65, 'appvendor.promise.procurement-vendor-dataperalatan', NULL, 0, NULL, 'menu.settingvendor.data_peralatan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (82, '2015-11-30 09:02:33', NULL, 'icon-play', 0, 'Seleksi Pendaftaran', 1, 'app.promise.procurement-panitia-seleksipendaftaran-index', NULL, 0, NULL, 'menu.prosespengadaan.seleksi_pendaftaran');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (83, '2016-1-7 17:00:00', NULL, 'fa fa-trello', 0, 'Pra Pengadaan', NULL, NULL, NULL, 1, NULL, 'menu.prapengadaan.modul_prapengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (84, '2016-1-8 08:19:47', NULL, 'icon-play', 0, 'Kriteria Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-kriteriakualifikasi', NULL, 8, NULL, 'menu.prapengadaan.kriteria_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (85, '2015-11-30 07:12:41', NULL, 'icon-play', 0, 'Kriteria Kualifikasi Administrasi', 19, 'app.promise.procurement-master-kriteriaKualifikasiAdministrasi', NULL, 0, 0, 'menu.masterdata.kriteria_kualifikasi_administrasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (86, '2015-11-30 07:12:41', NULL, 'icon-play', 0, 'Parameter', 20, 'app.promise.procurement-master-parameter', NULL, 0, 0, 'menu.settingadmin.parameter');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (88, '2015-1-12 07:12:41', NULL, 'icon-play', 0, 'Dashboard Panitia', NULL, 'app.dashboard', NULL, 0, 0, NULL);
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (89, '2015-1-12 07:12:41', NULL, 'icon-play', 0, 'Dashboard Vendor', NULL, 'appvendor.promise.dashboard', NULL, 0, 0, NULL);
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (90, '2015-11-30 09:03:39', NULL, 'icon-play', 0, 'Data Penawaran Tahap Dua', 58, 'appvendor.promise.procurement-vendor-datapenawarantahapdua-index', NULL, 0, NULL, 'menu.prosespengadaanvendor.data_penawaran_tahap_dua');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (91, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Pembukaan Penawaran Tahap Satu', 1, 'app.promise.procurement-panitia-pembukaanPenawaran', NULL, 0, 0, 'menu.prosespengadaan.pembukaan_penawaran_tahap_satu');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (92, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Pembukaan Penawaran Tahap Dua', 1, 'app.promise.procurement-panitia-pembukaanPenawaran', NULL, 0, 0, 'menu.prosespengadaan.pembukaan_penawaran_tahap_dua');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (96, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Penyampaian Sanggahan', 58, 'appvendor.promise.procurement-vendor-sanggahan', NULL, 0, 0, 'menu.prosespengadaanvendor.penyampaian_sanggahan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (97, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Sanggahan', 1, 'app.promise.procurement-panitia-sanggahan', NULL, 0, 0, 'menu.prosespengadaan.sanggahan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (98, '2015-11-30 06:54:53', NULL, 'icon-layers', 0, 'Anggaran', NULL, NULL, NULL, 1, 0, 'menu.anggaran.modul_anggaran');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (99, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Alokasi Anggaran', 98, 'app.promise.procurement-panitia-alokasianggaran', NULL, 1, 0, 'menu.anggaran.alokasi_anggaran');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (100, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Anggaran Gabungan', 98, 'app.promise.procurement-panitia-alokasianggaran-gabung', NULL, 3, 0, 'menu.anggaran.anggaran_gabungan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (101, '2015-11-30 06:54:53', NULL, 'icon-clock', 0, 'Perencanaan', NULL, NULL, NULL, 1, 0, 'menu.perencanaan.modul_perencanaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (102, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Perencanaan Pengadaan', 101, 'app.promise.procurement-panitia-perencanaan', NULL, 0, 0, 'menu.perencanaan.perencanaan_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (206, '2016-8-25 07:00:29', NULL, 'icon-play', 0, 'Purchase Request', 101, 'app.promise.procurement-purchaserequest', NULL, 0, NULL, 'menu.perencanaan.purchase_request');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (103, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Pengumuman Evaluasi Admin Teknis', 1, 'app.promise.procurement-panitia-pengumumanevaluasiadminteknis', NULL, 0, 0, 'menu.prosespengadaan.pengumuman_evaluasi_admin_teknis');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (104, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Persetujuan Pengadaan', 1, 'app.promise.procurement-panitia-persetujuanpengadaan', NULL, 4, 0, 'menu.prosespengadaan.persetujuan_pengadaan');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (105, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Jadwal Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-jadwalkualifikasi', NULL, 5, 0, 'menu.prapengadaan.jadwal_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (106, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Pengambilan Dokumen Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-pengambilandokumenkualifikasi', NULL, 7, 0, 'menu.prapengadaan.pengambilan_dokumen_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (107, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Pemasukan Dokumen Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-pemasukandokumenkualifikasi', NULL, 8, 0, 'menu.prapengadaan.pemasukan_dokumen_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (108, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Seleksi Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-seleksikualifikasi', NULL, 9, 0, 'menu.prapengadaan.seleksi_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (109, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Hasil Kualifikasi', 83, 'app.promise.procurement-panitia-prakualifikasi-hasilkualifikasi', NULL, 10, 0, 'menu.prapengadaan.hasil_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (111, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Pembuktian Kualifikasi', 1, 'app.promise.procurement-panitia-pembuktiankualifikasi', NULL, 11, 0, 'menu.prosespengadaan.pembuktian_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (112, '2015-11-19 17:00:00', NULL, 'icon-loader', 0, 'Pengadaan 1 Sampul', NULL, NULL, NULL, 5, NULL, NULL);
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (113, '2015-11-19 17:00:00', NULL, 'icon-loader', 0, 'Pengadaan 2 Sampul', NULL, NULL, NULL, 6, NULL, NULL);
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (114, '2015-11-19 17:00:00', NULL, 'icon-loader', 0, 'Pengadaan 2 Tahap', NULL, NULL, NULL, 7, NULL, NULL);
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (115, '2015-11-19 17:00:00', NULL, 'icon-loader', 0, 'Pemenang Pengadaan', NULL, NULL, NULL, 8, NULL, NULL);
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (116, '2015-11-30 06:59:26', NULL, 'icon-server', 0, 'Penilaian Vendor', 73, 'app.promise.procurement-manajemenvendor-penilaian', NULL, 3, NULL, 'menu.manajemenvendor.penilaian_vendor');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (117, '2015-11-21 08:19:47', NULL, 'icon-play', 0, 'Inisialisasi Pengadaan Versi 04', 83, 'app.promise.procurement-inisialisasi-index04', NULL, 1, NULL, 'menu.prapengadaan.inisialisasi_pengadaan4');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (118, '2015-11-21 08:19:47', NULL, 'icon-play', 0, 'Usulan Calon Pememenang', 1, 'app.promise.procurement-panitia-usulancalonpemenang', NULL, 1, NULL, 'menu.prosespengadaan.usulan_calon_pemenang');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (119, '2015-11-21 08:19:47', NULL, 'icon-play', 0, 'Alokasi Anggaran - Versi 02', 98, 'app.promise.procurement-alokasianggaran-index02', NULL, 2, NULL, 'menu.anggaran.alokasi_anggaran2');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (200, '2016-1-7 17:00:00', NULL, 'fa fa-trello', 0, 'Pra Pengadaan - Kualifikasi', NULL, NULL, NULL, 1, NULL, 'menu.prapengadaanvendor.modul_prapengadaan_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (201, '2016-1-7 17:00:00', NULL, 'icon-play', 0, 'Undangan Kualifikasi', 200, 'appvendor.promise.procurement-prakualifikasi-undanganvendorkualifikasi', NULL, 1, NULL, 'menu.prapengadaanvendor.undangan_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (202, '2016-1-7 17:00:00', NULL, 'icon-play', 0, 'Pengumuman Kualifikasi', 200, 'appvendor.promise.procurement-prakualifikasi-pengumumankualifikasi', NULL, 2, NULL, 'menu.prapengadaanvendor.pengumuman_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (203, '2016-1-7 17:00:00', NULL, 'icon-play', 0, 'Data Kualifikasi', 200, 'appvendor.promise.procurement-prakualifikasi-datakualifikasi', NULL, 3, NULL, 'menu.prapengadaanvendor.data_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (204, '2015-11-30 06:54:53', NULL, 'icon-play', 0, 'Hasil Kualifikasi', 200, 'appvendor.promise.procurement-panitia-prakualifikasi-hasilkualifikasi', NULL, 10, 0, 'menu.prapengadaanvendor.hasil_kualifikasi');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (300, '2016-1-7 17:00:00', NULL, 'fa fa-trello', 0, 'Approval', NULL, NULL, NULL, 0, NULL, 'menu.approval.modul_approval');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (302, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Daftar Approval', 300, 'app.promise.procurement-approval', NULL, 0, 0, 'menu.approval.daftar_approval');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (301, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Approval Master', 20, 'app.promise.procurement-master-approval', NULL, 0, 0, 'menu.approval.approval_master');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (303, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Approval History', 300, 'app.promise.procurement-approval-history', NULL, 0, 0, 'menu.approval.approval_history');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (400, '2016-1-7 17:00:00', NULL, 'fa fa-trello', 0, 'Purchase Order', NULL, NULL, NULL, 50, NULL, 'menu.purchaseorder.modul_purchase_order');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (401, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Purchase Order Manager', 400, 'app.promise.procurement-purchaseorder', NULL, 0, 0, 'menu.purchaseorder.purchase_order_manager');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (410, '2015-11-30 07:07:28', NULL, 'fa fa-trello', 0, 'Purchase Request Verification', NULL, NULL, NULL, 2, 0, 'menu.purchaserequestverification.modul_purchase_request_verification');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (411, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Purchase Request Verification', 410, 'app.promise.procurement-purchaserequestverification', NULL, 0, 0, 'menu.purchaserequestverification.purchase_request_verification');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (500, '2016-1-7 17:00:00', NULL, 'fa fa-trello', 0, 'Request For Quotation', NULL, NULL, NULL, 20, NULL, 'menu.requestforquotation.modul_request_for_quotation');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (501, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'RFQ Manager', 500, 'app.promise.procurement-requestforquotation', NULL, 0, 0, 'menu.requestforquotation.rfq_manager');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (600, '2016-1-7 17:00:00', NULL, 'fa fa-trello', 0, 'Delivery Received', NULL, NULL, NULL, 60, NULL, 'menu.deliveryreceived.modul_delivery_received');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (601, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Delivery Received Manager', 600, 'app.promise.procurement-deliveryreceived', NULL, 0, 0, 'menu.deliveryreceived.delivery_received_manager');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (602, '2016-1-7 17:00:00', NULL, 'fa fa-trello', 0, 'Delivery Received', NULL, NULL, NULL, 2, NULL, 'menu.deliveryreceivedvendor.modul_delivery_received');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (603, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Delivery Received Manager', 602, 'appvendor.promise.procurement-deliveryreceived', NULL, 0, 0, 'menu.deliveryreceivedvendor.delivery_received_manager');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (605, '2015-11-30 06:59:26', NULL, 'icon-server', 0, 'Catalog', NULL, NULL, NULL, 0, NULL, 'menu.catalog.modul_catalog');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (604, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Attribute', 605, 'app.promise.procurement-master-attribute', NULL, 0, 0, 'menu.catalog.attribute');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (606, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Attribute Group', 605, 'app.promise.procurement-attribute-group', NULL, 0, 0, 'menu.catalog.attribute_group');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (607, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Category', 605, 'app.promise.procurement-category', NULL, 0, 0, 'menu.catalog.category');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (608, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Manage Catalog', 605, 'app.promise.procurement-catalog', NULL, 0, 0, 'menu.catalog.manage_catalog');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (609, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'View Vendor', 605, 'app.promise.procurement-catalog-vendor', NULL, 0, 0, 'menu.catalog.view_vendor');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (610, '2016-1-7 17:00:00', NULL, 'fa fa-trello', 0, 'KPI Monitoring ', NULL, NULL, NULL, 70, NULL, 'menu.kpimonitoring.modul_kpi_monitoring');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (611, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Monitoring', 610, 'app.promise.procurement-kpimonitoring', NULL, 0, 0, 'menu.kpimonitoring.monitoring');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (612, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'View Catalog', 605, 'app.promise.procurement-ecatalog2', NULL, 0, 0, 'menu.catalog.view_catalog');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (700, '2015-11-30 06:59:26', NULL, 'icon-search', 0, 'Invoice Monitoring', NULL, NULL, NULL, 80, NULL, 'menu.invoicemonitoring.modul_invoice_monitoring');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (701, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Invoice Matching', 700, 'app.promise.procurement-invoicematching', NULL, 0, 0, 'menu.invoicemonitoring.invoice_matching');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (710, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Alur Pengadaan 02', 20, 'app.promise.procurement-master-alurpengadaan-02', NULL, 2, 0, 'menu.settingadmin.alur_pengadaan_02');
INSERT INTO promise_t1_menu (MENU_ID, CREATED, DELETED, ICON, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, URUTAN, USERID, MENU_TRANSLATE) VALUES (1001, '2015-11-30 07:07:28', NULL, 'icon-play', 0, 'Data Sertifikat', 65, 'appvendor.promise.procurement-vendor-datasertifikat', NULL, 0, 0, 'menu.settingvendor.data_sertifikat');

#Pengadaan Gagal
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON, URUTAN) VALUES(1010, '2015-11-30 06:59:26', NULL, 0, 'Pengadaan Gagal', NULL, NULL, NULL, NULL, 'icon-delete', 80);
INSERT INTO T1_MENU (MENU_ID, CREATED, DELETED, ISDELETE, NAMA, PARENT_ID, PATH, UPDATED, USERID, ICON) VALUES(1011, '2015-11-30 07:07:28', NULL, 0, 'Pengadaan Gagal', 1010, 'app.promise.procurement-panitia-pengadaangagal', NULL, 0, 'icon-play');
