
package sap.interfacing.soap.po;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

import org.jboss.logging.Logger;

import id.co.promise.procurement.purchaseorder.PurchaseOrderItemServices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-12-01T23:05:47.576+08:00
 * Generated source version: 2.7.2
 * 
 */
public final class SICRTPOOB_HTTPSPort_Client {
	final static Logger log = Logger.getLogger(SICRTPOOB_HTTPSPort_Client.class);
    private static final QName SERVICE_NAME = new QName("urn:crt_purch_order", "SI_CRT_PO_OBService");

    private SICRTPOOB_HTTPSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICRTPOOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SICRTPOOBService ss = new SICRTPOOBService(wsdlURL, SERVICE_NAME);
        SICRTPOOB port = ss.getHTTPSPort();  
        
        {
        log.info("Invoking siCRTPOOB...");
        sap.interfacing.soap.po.ZFMCRTPO _siCRTPOOB_parameters = null;
        sap.interfacing.soap.po.ZFMCRTPOResponse _siCRTPOOB__return = port.siCRTPOOB(_siCRTPOOB_parameters);
        log.info("siCRTPOOB.result=" + _siCRTPOOB__return);


        }

        System.exit(0);
    }

}
