package sap.interfacing.soap.po;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2020-12-01T23:05:47.666+08:00
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "urn:crt_purch_order", name = "SI_CRT_PO_OB")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICRTPOOB {

    @WebResult(name = "ZFM_CRT_PO.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    @WebMethod(operationName = "SI_CRT_PO_OB", action = "http://sap.com/xi/WebService/soap1.1")
    public ZFMCRTPOResponse siCRTPOOB(
        @WebParam(partName = "parameters", name = "ZFM_CRT_PO", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
        ZFMCRTPO parameters
    );
}
