package sap.interfacing.soap.pr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2020-11-17T10:00:14.387+07:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "urn:crt_purch_requisition", name = "SI_CRT_PR_OB")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICRTPROB {

    @WebResult(name = "ZFM_CRT_PR.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    @WebMethod(operationName = "SI_CRT_PR_OB", action = "http://sap.com/xi/WebService/soap1.1")
    public ZFMCRTPRResponse siCRTPROB(
        @WebParam(partName = "parameters", name = "ZFM_CRT_PR", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
        ZFMCRTPR parameters
    );
}
