
package sap.interfacing.soap.pr;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

import org.jboss.logging.Logger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2020-11-17T10:00:14.281+07:00
 * Generated source version: 2.7.10
 * 
 */
public final class SICRTPROB_HTTPSPort_Client {
	final static Logger log = Logger.getLogger(SICRTPROB_HTTPPort_Client.class);
    private static final QName SERVICE_NAME = new QName("urn:crt_purch_requisition", "SI_CRT_PR_OBService");

    private SICRTPROB_HTTPSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICRTPROBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SICRTPROBService ss = new SICRTPROBService(wsdlURL, SERVICE_NAME);
        SICRTPROB port = ss.getHTTPSPort();  
        
        {
        log.info("Invoking siCRTPROB...");
        sap.interfacing.soap.pr.ZFMCRTPR _siCRTPROB_parameters = null;
        sap.interfacing.soap.pr.ZFMCRTPRResponse _siCRTPROB__return = port.siCRTPROB(_siCRTPROB_parameters);
        log.info("siCRTPROB.result=" + _siCRTPROB__return);


        }

        System.exit(0);
    }

}
