
package sap.interfacing.soap.pr;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.math.BigDecimal;
import java.net.Authenticator;
import java.net.MalformedURLException;
import java.net.PasswordAuthentication;
import java.net.URL;
import java.util.List;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;

import org.jboss.logging.Logger;

import id.co.promise.procurement.purchaseorder.PurchaseOrderItemServices;
import sap.interfacing.soap.pr.ZFMCRTPR.GTACCOUNTS;
import sap.interfacing.soap.pr.ZFMCRTPR.GTITEM;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2020-11-17T10:00:14.365+07:00
 * Generated source version: 2.7.10
 * 
 */
public final class SICRTPROB_HTTPPort_Client {
	final static Logger log = Logger.getLogger(SICRTPROB_HTTPPort_Client.class);
    private static final QName SERVICE_NAME = new QName("urn:crt_purch_requisition", "SI_CRT_PR_OBService");
    
    static class MyAuthenticator extends Authenticator {
		private String SAP_USERNAME = "basisxiqas";
		private String SAP_PASSWORD ="12345678";
		public PasswordAuthentication getPasswordAuthentication() {
			return (new PasswordAuthentication(SAP_USERNAME, SAP_PASSWORD.toCharArray()));
		}
	}
    
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICRTPROBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SICRTPROBService ss = new SICRTPROBService(wsdlURL, SERVICE_NAME);
        SICRTPROB port = ss.getHTTPPort();  
        String SAP_USERNAME = "basisxiqas";
		String SAP_PASSWORD ="12345678";
        BindingProvider prov = (BindingProvider)port;
		prov.getRequestContext().put(BindingProvider.USERNAME_PROPERTY, SAP_USERNAME);
		prov.getRequestContext().put(BindingProvider.PASSWORD_PROPERTY, SAP_PASSWORD);
        
        {
        log.info("Invoking siCRTPROB...");
        sap.interfacing.soap.pr.ZFMCRTPR _siCRTPROB_parameters = null;
        
        GTITEM gTITEM =  new GTITEM();
		List<ZSTPRITEM> zSTPRITEMList = gTITEM.getItem();
			
		
		GTACCOUNTS gTACCOUNTS =  new GTACCOUNTS();
		List<ZSTPRACC> zSTPRACCList = gTACCOUNTS.getItem();
		
		// Item					
		ZSTPRITEM item = new ZSTPRITEM();
		item.setPREQITEM("00010");
		item.setACCTASSCAT("K");
		item.setPURGROUP("PBJ");
		item.setPREQNAME("Mansar");
		item.setMATERIAL("50000013");
		item.setSHORTTEXT("Printer Laser");
		BigDecimal bd1 = new BigDecimal(10);
		item.setQUANTITY(bd1);
		item.setUNIT("PC");
		BigDecimal bd2 = new BigDecimal(10000);
		item.setPREQPRICE(bd2);
		item.setPREQDATE("2020-11-16");
		item.setDELIVDATE("2020-12-31");
		item.setPLANT("B010");
		item.setSTORELOC("KB10");
		item.setMATLGROUP("ZOS");
		item.setCURRENCY("IDR");
		item.setTRACKINGNO("");
		zSTPRITEMList.add(item);

		
		//list acount
		ZSTPRACC accounts = new ZSTPRACC();
		accounts.setPREQITEM("00010");
		accounts.setQUANTITY(bd1);
		accounts.setGLACCOUNT("4112221410");
		accounts.setBUSAREA("B010");
		accounts.setCOSTCENTER("21014000");
		accounts.setSERIALNO("");
		zSTPRACCList.add(accounts);

		
//		zSTPRACCList.add(accounts);
		
		//Header
		ZFMCRTPR zFMCRTPR = new ZFMCRTPR();
		zFMCRTPR.setGVATTACHMENT("1 Bundel");
		zFMCRTPR.setGVDOCTYPE("ZPR1");
		zFMCRTPR.setGVHEADERNOTE("Pembelian ATK");
		zFMCRTPR.setGVINTERMSOF("Berdasarkan NOTA xxx");
		zFMCRTPR.setGVREQUISITIONER("Mansar");
		zFMCRTPR.setGVTESTRUN("");
		zFMCRTPR.setGTITEM(gTITEM);
		zFMCRTPR.setGTACCOUNTS(gTACCOUNTS);
        
        sap.interfacing.soap.pr.ZFMCRTPRResponse _siCRTPROB__return = port.siCRTPROB(zFMCRTPR);
        log.info("siCRTPROB.result=" + _siCRTPROB__return);


        }

        System.exit(0);
    }

}
