package sap.interfacing.soap.rfq;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2020-11-10T11:08:25.341+07:00
 * Generated source version: 2.7.10
 * 
 */
@WebServiceClient(name = "RFQCreation_OutService", 
                  wsdlLocation = "file:/C:/Users/MMI5/AppData/Local/Temp/tempdir4345062136473331677.tmp/EPROC_SYSTEM_DEV_RFQCreation_Out_1.wsdl",
                  targetNamespace = "http://www.kereta-api.co.id/ERP/MM/EPROC/CrRFQ") 
public class RFQCreationOutService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.kereta-api.co.id/ERP/MM/EPROC/CrRFQ", "RFQCreation_OutService");
    public final static QName HTTPSPort = new QName("http://www.kereta-api.co.id/ERP/MM/EPROC/CrRFQ", "HTTPS_Port");
    public final static QName HTTPPort = new QName("http://www.kereta-api.co.id/ERP/MM/EPROC/CrRFQ", "HTTP_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/MMI5/AppData/Local/Temp/tempdir4345062136473331677.tmp/EPROC_SYSTEM_DEV_RFQCreation_Out_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RFQCreationOutService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/MMI5/AppData/Local/Temp/tempdir4345062136473331677.tmp/EPROC_SYSTEM_DEV_RFQCreation_Out_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RFQCreationOutService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RFQCreationOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RFQCreationOutService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RFQCreationOutService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RFQCreationOutService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RFQCreationOutService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RFQCreationOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public RFQCreationOut getHTTPSPort() {
        return super.getPort(HTTPSPort, RFQCreationOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RFQCreationOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public RFQCreationOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, RFQCreationOut.class, features);
    }
    /**
     *
     * @return
     *     returns RFQCreationOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public RFQCreationOut getHTTPPort() {
        return super.getPort(HTTPPort, RFQCreationOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RFQCreationOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public RFQCreationOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, RFQCreationOut.class, features);
    }

}
