
package sap.interfacing.soap.rfq;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

import org.jboss.logging.Logger;

import sap.interfacing.soap.pr.SICRTPROB_HTTPPort_Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2020-11-10T11:08:25.274+07:00
 * Generated source version: 2.7.10
 * 
 */
public final class RFQCreationOut_HTTPPort_Client {
	final static Logger log = Logger.getLogger(RFQCreationOut_HTTPPort_Client.class);
    private static final QName SERVICE_NAME = new QName("http://www.kereta-api.co.id/ERP/MM/EPROC/CrRFQ", "RFQCreation_OutService");

    private RFQCreationOut_HTTPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RFQCreationOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RFQCreationOutService ss = new RFQCreationOutService(wsdlURL, SERVICE_NAME);
        RFQCreationOut port = ss.getHTTPPort();  
        
        {
        log.info("Invoking rfqCreateReqSync...");
        sap.interfacing.soap.rfq.ZFMCRTRFQ2 _rfqCreateReqSync_parameters = null;
        sap.interfacing.soap.rfq.ZFMCRTRFQ2Response _rfqCreateReqSync__return = port.rfqCreateReqSync(_rfqCreateReqSync_parameters);
        log.info("rfqCreateReqSync.result=" + _rfqCreateReqSync__return);


        }

        System.exit(0);
    }

}
