package sap.interfacing.soap.rfq;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2020-11-10T11:08:25.308+07:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://www.kereta-api.co.id/ERP/MM/EPROC/CrRFQ", name = "RFQCreation_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RFQCreationOut {

    @WebResult(name = "ZFM_CRT_RFQ_2.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    @WebMethod(operationName = "RFQCreateReq_Sync", action = "http://sap.com/xi/WebService/soap1.1")
    public ZFMCRTRFQ2Response rfqCreateReqSync(
        @WebParam(partName = "parameters", name = "ZFM_CRT_RFQ_2", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
        ZFMCRTRFQ2 parameters
    );
}
